In [1]:
!pip install numpy


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
!python -m pip install --upgrade pip


  Using cached pip-25.3-py3-none-any.whl.metadata (4.7 kB)
Using cached pip-25.3-py3-none-any.whl (1.8 MB)
  Attempting uninstall: pip
    Found existing installation: pip 25.2
    Uninstalling pip-25.2:
      Successfully uninstalled pip-25.2


In [1]:
import numpy as np

In [2]:
np.__version__

'2.4.0'

creating array 

in numpy cant use list,set,tuple all in array


In [10]:
arr = np.random.randint(0,10,size = (3,4,3))

In [11]:
arr

array([[[9, 0, 3],
        [4, 7, 6],
        [8, 5, 1],
        [2, 1, 9]],

       [[9, 7, 4],
        [7, 1, 8],
        [7, 2, 5],
        [5, 4, 4]],

       [[4, 0, 6],
        [8, 3, 7],
        [9, 8, 6],
        [9, 4, 9]]], dtype=int32)

In [12]:
arr[0]

array([[9, 0, 3],
       [4, 7, 6],
       [8, 5, 1],
       [2, 1, 9]], dtype=int32)

In [20]:
arr[:2,:]

array([[[9, 0, 3],
        [4, 7, 6],
        [8, 5, 1],
        [2, 1, 9]],

       [[9, 7, 4],
        [7, 1, 8],
        [7, 2, 5],
        [5, 4, 4]]], dtype=int32)

In [21]:
dataset = np.random.randint(0,255,(16,3,720,720))

In [22]:
dataset

array([[[[245, 133, 132, ..., 160, 104, 106],
         [ 18,  20, 146, ...,  54,  88,  51],
         [ 88, 109,  73, ..., 220,  47, 174],
         ...,
         [206,  59, 117, ..., 177, 149, 219],
         [187,  75, 182, ...,  64, 104, 189],
         [  6, 214, 216, ..., 224,  56,  94]],

        [[211,  98,  62, ..., 110,  38, 118],
         [231,  42,  42, ..., 157,   5,  27],
         [ 34, 241, 144, ...,  99,  77, 103],
         ...,
         [  2,  68,  51, ...,  34, 106,  47],
         [ 53,   3, 170, ...,  60,  10,  73],
         [ 39,  27,  11, ...,  96,  75, 247]],

        [[224, 167,  60, ..., 185, 204,  55],
         [121, 174,  31, ...,  83,  36, 126],
         [ 40, 135, 178, ..., 213, 236,  99],
         ...,
         [ 98,  10, 236, ..., 218, 165,  51],
         [172, 239, 150, ..., 135, 170,  91],
         [141, 154,  82, ..., 184,  73, 215]]],


       [[[161, 141, 177, ...,  10,  24, 141],
         [ 47,  65,  28, ..., 201, 172, 205],
         [227, 179,   3, ..., 

In [23]:
dataset[0]

array([[[245, 133, 132, ..., 160, 104, 106],
        [ 18,  20, 146, ...,  54,  88,  51],
        [ 88, 109,  73, ..., 220,  47, 174],
        ...,
        [206,  59, 117, ..., 177, 149, 219],
        [187,  75, 182, ...,  64, 104, 189],
        [  6, 214, 216, ..., 224,  56,  94]],

       [[211,  98,  62, ..., 110,  38, 118],
        [231,  42,  42, ..., 157,   5,  27],
        [ 34, 241, 144, ...,  99,  77, 103],
        ...,
        [  2,  68,  51, ...,  34, 106,  47],
        [ 53,   3, 170, ...,  60,  10,  73],
        [ 39,  27,  11, ...,  96,  75, 247]],

       [[224, 167,  60, ..., 185, 204,  55],
        [121, 174,  31, ...,  83,  36, 126],
        [ 40, 135, 178, ..., 213, 236,  99],
        ...,
        [ 98,  10, 236, ..., 218, 165,  51],
        [172, 239, 150, ..., 135, 170,  91],
        [141, 154,  82, ..., 184,  73, 215]]],
      shape=(3, 720, 720), dtype=int32)

In [26]:
  b = np.random.randint(0,3,(3,4))

In [27]:
b

array([[2, 1, 1, 0],
       [2, 0, 1, 2],
       [0, 2, 0, 0]], dtype=int32)

In [28]:
  a = np.random.randint(0,3,(4,3))

In [29]:
a

array([[0, 0, 1],
       [0, 2, 2],
       [2, 1, 0],
       [0, 1, 0]], dtype=int32)

In [30]:
res = np.dot(b,a)

In [31]:
res

array([[2, 3, 4],
       [2, 3, 2],
       [0, 4, 4]], dtype=int32)

In [1]:
import numpy as np

In [5]:
import time

In [ ]:
a = 

In [4]:
st = time.time()

res = a * b

end = time.time()

NameError: name 'a' is not defined

In [ ]:
print